name: big_head_softwares
description: This package helps you to write code faster and be more productive. This package is provided by Bighead Softwares LLP feel free to use it in any manner you desire.
version: 0.0.2
homepage: https://github.com/bigheadSoftwares/easy_coding_by_bhs.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

